#!/bin/bash

FAN_DEVICE="${BLOCK_INSTANCE:-fan1}"
FAN_OUTPUT=$(sensors | grep "${FAN_DEVICE}")

RPM="$(echo "$FAN_OUTPUT" | awk -F' ' '{print $2}')"
UNIT="$(echo "$FAN_OUTPUT" | awk -F' ' '{print $3}')"

echo "${RPM} ${UNIT}"
echo "${RPM} ${UNIT}"
if [[ $((RPM)) -lt 500 ]]; then
    echo "#00FF00"
elif [[ $((RPM)) -lt 2500 ]]; then
    echo "#FFFF00"
elif [[ $((RPM)) -lt 4000 ]]; then
    echo "#FF800"
else
    echo "#FF0000"
fi

#if [[ ! -z "$FAN_DEVICE" ]] && [[ -f /var/log/i3/stats.log ]]; then
#    printf "%s\t%s\t%s\n" `date +'%s'` "$FAN_DEVICE" "$RPM" >> /var/log/i3/stats.log
#fi
