#!/bin/bash

SSID_NAME=$(/sbin/iwgetid -r)

# You can put any urgent name so the block will give warning
# if a network with this name is used, like public wifi or alike.
# You can separate multiple values with \|
URGENT_VALUE="50"

WLAN=$(/sbin/iwgetid | /usr/bin/awk -F' ' '{print $1}')
STRENGTH=$(/sbin/iwconfig "${WLAN}" | /bin/grep -Po "(?<=Link Quality=)[0-9/]+ " | /usr/bin/xargs -i echo "100*{}" | /usr/bin/bc)


if [[ "${SSID_NAME}" != "" && "${STRENGTH}" != "" ]]; then
    if [[ ${#SSID_NAME} -gt 10 ]]; then
        SSID_NAME=WiFi
    fi
    echo "${SSID_NAME} 📶 ${STRENGTH}%"
    echo "WiFi ${STRENGTH}%"

    if [[ $((STRENGTH)) -lt $((URGENT_VALUE)) ]]; then
        echo "#FF0000"
    else
        echo "#00FF00"
    fi
fi
