#!/bin/bash
INSTANCE=`pactl list short | grep RUNNING | head -1 | cut -f1`
SUSPENDED=""

if ! [[ -z "$INSTANCE" ]]; then
    if [[ $((BLOCK_BUTTON)) -eq 1 ]] || [[ $((BLOCK_BUTTON)) -eq 4 ]]; then
        pactl set-sink-volume ${INSTANCE} '+5%'
    elif [[ $((BLOCK_BUTTON)) -eq 2 ]]; then
        pactl set-sink-mute ${INSTANCE} toggle
    elif [[ $((BLOCK_BUTTON)) -eq 3 ]] || [[ $((BLOCK_BUTTON)) -eq 5 ]]; then
        pactl set-sink-volume ${INSTANCE} '-5%'
    fi
else
    INSTANCE=`pactl list short | grep SUSPENDED | head -1 | cut -f1`
    SUSPENDED="💀"
    if [[ -z "$INSTANCE" ]]; then
        echo "💀 N/A"
        echo "💀 N/A"
        echo "${COLOR}"
        exit 33
    fi
fi

STATUS_CMD="`dirname $0`/volume.pl"
MUTE=$(exec $STATUS_CMD "$INSTANCE" | grep 'MUTE' | cut -d: -f2 | tr -d ' ')
VOLUME=$(exec $STATUS_CMD "$INSTANCE" | grep 'VOLUME' | cut -d: -f2 | tr -d ' %')
HEADPHONES=$(exec $STATUS_CMD "$INSTANCE" | grep 'HEADPHONES' | cut -d: -f2 | tr -d ' %')
HEADPHONES_CONNECTED=""

if [[ "${HEADPHONES}" == "yes" ]]; then
    HEADPHONES_CONNECTED="🎧"
fi

COLOR="#ffffff"
if [[ "${MUTE}" == "yes" ]]; then
    LABEL="🔇"
    COLOR="#ffff00"
elif [[ $((VOLUME)) -gt 50 ]]; then
    LABEL="🔊"
elif [[ $((VOLUME)) -gt 20 ]]; then
    LABEL="🔉"
elif [[ $((VOLUME)) -gt 0 ]]; then
    LABEL="🔈"
else
    # oh-oh, not so goods
    echo "💀 N/A"
    echo "💀 N/A"
    echo "${COLOR}"
    exit 33
fi


echo "${LABEL} ${VOLUME}% ${HEADPHONES_CONNECTED} ${SUSPENDED}"
echo "${LABEL} ${VOLUME}% ${HEADPHONES_CONNECTED}"
echo "${COLOR}"
if [[ $((VOLUME)) -gt 100 ]]; then
    exit 33
fi

